#!/bin/bash

	POSITIONAL=()
	while [[ $# -gt 0 ]]; do
	key="$1"

	case $key in
		-e|--extension)
		EXTENSION="$2"
		shift # past argument
		shift # past value
		;;
		*)    # unknown option
		POSITIONAL+=("$1") # save it in an array for later
		shift # past argument
		;;
	esac
	done
	set -- "${POSITIONAL[@]}" # restore positional parameters

	if [ $# -ge 1 -a -f "$1" ]; then
		input="$1" 
	else
		input="-" 
		if [ -t 0 -o -z "$EXTENSION" ]; then
			echo "	
			=== bb_count_seqs ===
			
			bb_count_seqs: 
			Counts the number of fasta or fastq sequences in a file.
			
			Missing argument.
			
			Usage: 
			bb_count_seqs [INPUT FILE]
			cat [INPUT FILE] | bb_count_seqs --extension [EXTENSION NAME]
			
			Expects the following file extensions: .fasta, .fastq,
			.fa or .fq
			"	
			exit 0
		fi
	fi

	if [ "${1##*.}" = "fasta" ] || [ "${1##*.}" = "fa" ] || [ "$EXTENSION" = "fasta" ]; then

		grep -c '>' $input
		exit 0

	elif [ "${1##*.}" = "fastq" ] || [ "${1##*.}" = "fq" ] || [ "$EXTENSION" = 'fastq' ]; then

		x=$(wc -l $input | awk '{ print $1 }') 
		var3=$(bc <<< "$x / 4")
		echo $var3
		exit 0
	else
		echo "ERROR: Unable to process input file."
		echo "It seems your file is not fasta (.fasta, .fa) or fastq (.fastq, .fq) file."
	fi

	

