#!/bin/bash
#Comments: this can be helpful,Extracts from line 5 to 10 in input.txt file: sed -n '5,10 p' input.txt
	
	function help() {
	echo "
	=== bb_extract_fasta_entry ===
	
	bb_extract_fasta_entry: 
	Extracts a single fasta sequence from a multiple fasta file.
	
	Missing argument.
	
	Usage: 
	bb_extract_fasta_entry [INPUT FILE] [SEQUENCE IDs ... ]
	"
	exit 0
	}

	if [ $# -ge 1 -a -f "$1" ]; then
		input="$1" 
		shift 1
	else
		help
		exit 0
	fi

	#anchor finds the row number of the sequence to extract, it comes in the form:
	#line_number:fasta_header
	#120:>Prodigal Gene 2 # 2901 # 3311 # 1 is extracted with "cut"
	grep -nwf <(echo "$*" | tr " " "\n") "$input" |
	while read line; do
		#extract the line number
		anchor=${line%%:*}

		sed -n "$anchor"',/^>/ {
			'"$anchor"' p
			/^>/ !p
		}' "$input"	
	done
