#!/bin/bash
#Comments: this can be helpful,Extracts from line 5 to 10 in input.txt file: sed -n '5,10 p' input.txt
	function help() {
	echo "
	=== bb_extract_fasta_entry ===
	
	bb_extract_fasta_entry: 
	Extracts a single fasta sequence from a multiple fasta file.
	
	Missing argument.
	
	Usage: 
	bb_extract_fasta_entry [INPUT FILE] [SEQUENCE_IDs] ...
	"
	}
	
	# See if the first argument is equal to another argument
	in_args() {
		local _line=$1
		shift 1
		for f in $* ; do
			if [ $f == $_line ]; then 
				return 0
			fi
		done
		return 1
	}

	if [ $# -ge 1 -a -f "$1" ]; then
		input="$1" 
		shift 1
	else
		if [[ -t 0 ]]; then
			help
			exit 0
		fi
	fi

	match=1

	cat $input | while read line; do
		# if the line begins with ">" is_header = 1
		is_header=$(echo "$line" | grep -c '^>')
		if [ $is_header -lt 1 ]; then
			# If inside a matching entry print contents
			[[ $match -eq 0 ]] && echo "$line"
		else
			# Check if the entry header is the arguments list
			if in_args ${line:1} $* ; then
				echo $line
				match=0
			else 
				match=1
			fi
		fi
	done
