#!/bin/bash
#This script was adapted from:
# https://bioinformaticsworkbook.org/dataWrangling/fastaq-manipulations/converting-fastq-format-to-fasta.html#gsc.tab=0

	function help() {
	echo "
	=== bb_fastq2fasta ===
	
	bb_fastq2fasta: 
	Converts fastq into fasta.
	
	Missing argument.
	
	Usage: 
	bb_fastq2fasta: [INPUT FILE]
	"
	}

	if [ $# -ge 1 -a -f "$1" ]; then
		input="$1" 
	else
		input="-" 
		if [[ -t 0 ]]; then
			help
			exit 0
		fi
	fi

	#Read every 4 lines
	sed -n --expression='1~4s/^@/>/p;2~4p' $input
