#!/bin/bash

	function help() {
	echo "
	=== bb_get_GC_content ===
	
	bb_get_GC_content: 
	Gets the GC percentage of a file.
	
	Missing argument.
	
	Usage: 
	bb_get_GC_content [INPUT FILE]
	"
	}

	LOCATION_TMP_FILE="/tmp/$RANDOM"

	if [ $# -ge 1 -a -f "$1" ]; then
		input="$1" 
	else 
		if [ -t 0 ]; then
			help
			exit 0
		fi
	fi
	
	cat $input > $LOCATION_TMP_FILE

	isMultiple=$(grep -c '>' $LOCATION_TMP_FILE)

	if [ "$isMultiple" -gt "1" ] ; then
		echo "This is a multiple fasta file. You need a single fasta file."
		help
		exit
	fi

	numResidues=$(bb_count_residues $LOCATION_TMP_FILE)
	g=$(cat $LOCATION_TMP_FILE | sed -e '/^>/d' | tr -d '\n' | grep -oi 'G' | wc -l | awk '{print $1}')
	c=$(cat $LOCATION_TMP_FILE | sed -e '/^>/d' | tr -d '\n' | grep -oi 'C' | wc -l | awk '{print $1}')
	perc=$(echo "(($g+$c)*100)/$numResidues" | bc -l)
	echo "$perc"
	rm $LOCATION_TMP_FILE
	#brute force algorithm above, can be improved using AWK's split function:
	#http://stackoverflow.com/questions/8009664/split-string-to-array-using-awk
	#or with the following code corrected (take out end of line chars)
	#noHead=$(bb_remove_fasta_header $1)
	#nonAT=$(echo "$noHead" | tr -d 'AaTt\n')
	#echo "$nonAT"
	#echo "$nonAT" | wc -m
	
	

	
