#!/bin/bash

	function help() {
	echo "
	=== bb_get_GC_content ===
	
	bb_get_GC_content: 
	Gets the GC percentage of a file.
	
	Missing argument.
	
	Usage: 
	bb_get_GC_content [INPT FILE]
	"
	}

	if [ -z "$1" ] ; then
		help
		exit 0
	fi

	isMultiple=$(grep -c '>' $1)

	if [ "$isMultiple" -gt "1" ] ; then
		echo "This is a multiple fasta file. You need a single fasta file."
		help
		exit
	fi

	numResidues=$(bb_count_residues $1)
	g=$(cat $1 | sed -e '/^>/d' | tr -d '\n' | grep -oi 'G' | wc -l | awk '{print $1}')
	c=$(cat $1 | sed -e '/^>/d' | tr -d '\n' | grep -oi 'C' | wc -l | awk '{print $1}')
	perc=$(echo "(($g+$c)*100)/$numResidues" | bc)
	echo "$perc"
	#brute force algorithm above, can be improved using AWK's split function:
	#http://stackoverflow.com/questions/8009664/split-string-to-array-using-awk
	#or with the following code corrected (take out end of line chars)
	#noHead=$(bb_remove_fasta_header $1)
	#nonAT=$(echo "$noHead" | tr -d 'AaTt\n')
	#echo "$nonAT"
	#echo "$nonAT" | wc -m
		
	
