#!/bin/bash
	
	function help() {
	echo "
	=== bb_get_nr_list ===
	
	bb_get_nr_list: 
	Given a one colum file with a list of items, this 
	function outputs a new version of the list where 
	redundant items are removed from the list. 
	This means that	if the file has the items: 
	A, B, A, B, D, C and D. 
	The output will be: A, B, C and D (in one column 
	format).
	
	Missing argument.
	
	Usage: 
	bb_get_nr_list [INPUT FILE]
	"
	}

	if [ $# -ge 1 -a -f "$1" ]; then
		input="$1" 
	else
		if [[ -t 0 ]]; then
			help
			exit 0
		fi
	fi
	
	FILEA=$(bb_create_tmp_file)
	FILEB=$(bb_create_tmp_file)
	FILEC=$(bb_create_tmp_file)
	
	cat $input | sort  > $FILEA
	uniq -u $FILEA > $FILEB
	uniq -d $FILEA > $FILEC
	cat $FILEB $FILEC | sort
	
